<a href="https://colab.research.google.com/github/parth025sharma/ML/blob/master/tensor_mun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
# to assign fix value in tensorflow we need to define constant
x=tf.constant([30])

In [0]:
x1=tf.constant([3,5,66,88]) # multi value constant

In [0]:
# y 
y=tf.constant(20)

In [0]:
#equation
z=x+y # new tensor --------- z equation compile and store and wait for resources
# CPU,GPU,TPU

In [0]:
# we have another method to add the same
z1=tf.add(x,y)

In [0]:
# now time for assigning resources to our equation
sess=tf.Session() # connect CPU,GPU,TPU

In [0]:
# now we can run our equation
output=sess.run(z)

In [0]:
output

array([50], dtype=int32)

In [0]:
#clossing session
sess.close()

In [0]:
# we can perform same task in another way
with tf.Session() as sess:
  output1=sess.run(z)
  tf.summary.FileWriter(sess.graph)
# in this session get auto closed
#another way where we don't need to close the session

In [0]:
output1


array([50], dtype=int32)

#Placeholder

In [0]:
# first place holder
t1=tf.placeholder(tf.int32)

In [0]:
# second place holder
t2=tf.placeholder(tf.int32)

In [0]:
#adding values
sum=tf.add(t1,t2)

In [0]:
# general
sum1=t1+t2

In [0]:
# time for creating session
with tf.Session() as sess:
  output2=sess.run(sum,{t1:[3,6],t2:[5,8]})
  #output2=sess.run(sum1,{t1:[3,6],t2:[5,8]})
  # boths output are same

In [46]:
output2

array([ 8, 14], dtype=int32)